package frames;

import clases.Sesion;
import conexionBD.registro_UsuariosBD;
import conexionBD.Rol;
import conexionBD.RolBD;
import conexionBD.Usuario;
import java.awt.Dimension;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class editarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private boolean mostrarContrasenia = false;
    private boolean mostrarContrasenia2 = false;
    private Usuario usuarioAEditar;
    
    public editarUsuario(Usuario usuario) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.setSize(new Dimension(400,580));
        
        
        cargarRoles();

        this.usuarioAEditar = usuario;

    // Precargar datos
        txtNombre.setText(usuario.getNombre());
        txtCorreo.setText(usuario.getEmail());

        for (int i = 0; i < comboRol.getItemCount(); i++) {
            Rol rol = comboRol.getItemAt(i);
            if (rol.getNombre().equalsIgnoreCase(usuario.getRol())) {
                comboRol.setSelectedIndex(i);
                break;
            }
        }

        txtContrasena.setEnabled(false);
        txtRepetirContrasena.setEnabled(false);

        // Listener para checkbox modificar contraseña
        jCheckBox1.addActionListener(e -> {
            boolean seleccionado = jCheckBox1.isSelected();
            txtContrasena.setEnabled(seleccionado);
            txtRepetirContrasena.setEnabled(seleccionado);
        });
    }
    
    private void cargarRoles() {
        RolBD rolDAO = new RolBD();
        List<Rol> roles = rolDAO.obtenerRoles();

        for (Rol rol : roles) {
            // Si el usuario no es admin, oculta los roles admin y supervisor
            if (!Sesion.esAdmin()) {
                String nombreRol = rol.getNombre().toLowerCase();
                if (nombreRol.equals("admin") || nombreRol.equals("administrador") || nombreRol.equals("supervisor")) {
                    continue;
                }
            }
            comboRol.addItem(rol);
        }
    }
    
    private boolean esCorreoValido(String correo) {
        String regex = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
        return correo.matches(regex);
    }

    
    private void actualizarUsuario() {
    String nombre = txtNombre.getText().trim();
    String correo = txtCorreo.getText().trim();
    String contrasena = new String(txtContrasena.getPassword());
    String repetirContrasena = new String(txtRepetirContrasena.getPassword());
    boolean modificarContrasena = jCheckBox1.isSelected();

    // Validaciones
    if (nombre.isEmpty() || correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nombre y correo son obligatorios.");
        return;
    }

    if (!esCorreoValido(correo)) {
        JOptionPane.showMessageDialog(this, "El formato del correo no es válido.");
        return;
    }

    if (modificarContrasena) {
        if (contrasena.isEmpty() || repetirContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar y repetir la contraseña.");
            return;
        }

        if (!contrasena.equals(repetirContrasena)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }
    }

    // Confirmación
    int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas guardar los cambios?", "Confirmar", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;

    Rol rolSeleccionado = (Rol) comboRol.getSelectedItem();
    int rolId = rolSeleccionado != null ? rolSeleccionado.getId() : -1;

    boolean exito = registro_UsuariosBD.actualizarUsuario(usuarioAEditar.getId(), nombre, correo, modificarContrasena ? contrasena : null, rolId);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Error al actualizar usuario.");
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPassw = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabelPassw1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        comboRol = new javax.swing.JComboBox<>();
        txtContrasena = new javax.swing.JPasswordField();
        txtRepetirContrasena = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel1.setText("Editar Usuario");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabelPassw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view.png"))); // NOI18N
        jLabelPassw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPasswMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("Correo");

        jTextField3.setText("jTextField3");

        jLabelPassw1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view.png"))); // NOI18N
        jLabelPassw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPassw1MouseClicked(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Repetir contraseña");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("Rol");

        jCheckBox1.setText("Modificar contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRepetirContrasena)
                            .addComponent(txtContrasena)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassw)
                            .addComponent(jLabelPassw1))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPassw))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPassw1))
                        .addGap(26, 26, 26)
                        .addComponent(btnAceptar)
                        .addGap(1863, 1863, 1863)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPasswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPasswMouseClicked
        // TODO add your handling code here:
        if(mostrarContrasenia) {
            txtContrasena.setEchoChar('*');
            jLabelPassw.setIcon(new ImageIcon(getClass().getResource("/img/view.png")));
            mostrarContrasenia = false;
        } else{
            txtContrasena.setEchoChar((char) 0);
            jLabelPassw.setIcon(new ImageIcon(getClass().getResource("/img/hide.png")));
            mostrarContrasenia = true;
        }
        
    }//GEN-LAST:event_jLabelPasswMouseClicked

    private void jLabelPassw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPassw1MouseClicked
        // TODO add your handling code here:
        if(mostrarContrasenia2) {
            txtRepetirContrasena.setEchoChar('*');
            jLabelPassw1.setIcon(new ImageIcon(getClass().getResource("/img/view.png")));
            mostrarContrasenia2 = false;
        } else{
            txtRepetirContrasena.setEchoChar((char) 0);
            jLabelPassw1.setIcon(new ImageIcon(getClass().getResource("/img/hide.png")));
            mostrarContrasenia2 = true;
        }
    }//GEN-LAST:event_jLabelPassw1MouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        actualizarUsuario();
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<conexionBD.Rol> comboRol;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPassw;
    private javax.swing.JLabel jLabelPassw1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtRepetirContrasena;
    // End of variables declaration//GEN-END:variables
}
