/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clases.Sesion;
import conexionBD.Usuario;
import javax.swing.ImageIcon;

/**
 *
 * @author azael
 */
public class perfil extends javax.swing.JFrame {

    /**
     * Creates new form perfil
     */
    public perfil() {
        initComponents();
        cargarDatosUsuario();
        //probarCargaImagen();
        setLocationRelativeTo(null);
    }
    
    /*public void probarCargaImagen() {
        java.net.URL url = getClass().getResource("/img/user.png");
        if (url != null) {
            System.out.println("Imagen encontrada en: " + url);
            ImageIcon icon = new ImageIcon(url);
            tarjetaPerfil1.setImagenPerfil(icon);
        } else {
            System.err.println("No se encontró la imagen en /img/user.png");
        }
    }*/
    
    private void cargarDatosUsuario() {
        Usuario usuario = Sesion.getUsuarioActual();

        if (usuario != null) {
            tarjetaPerfil1.setNombre(usuario.getNombre());
            tarjetaPerfil1.setCorreo(usuario.getEmail());
            tarjetaPerfil1.setRol(usuario.getRol());

            switch (usuario.getRol().toLowerCase()) {
                case "admin":
                    tarjetaPerfil1.setDescripcion("Administrador del sistema con todos los permisos.");
                    tarjetaPerfil1.setImagenPerfilDesdeRecurso("/img/clientes.png");
                    break;
                case "cajero":
                    tarjetaPerfil1.setDescripcion("Encargado de las operaciones de caja.");
                    tarjetaPerfil1.setImagenPerfilDesdeRecurso("/img/user.png");
                    break;
                case "supervisor":
                    tarjetaPerfil1.setDescripcion("Supervisa el funcionamiento y al personal.");
                    tarjetaPerfil1.setImagenPerfilDesdeRecurso("/img/user.png");
                    break;
                default:
                    tarjetaPerfil1.setDescripcion("Rol no reconocido");
                    tarjetaPerfil1.setImagenPerfilDesdeRecurso("/img/user.png");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tarjetaPerfil1 = new componente.TarjetaPerfil();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tarjetaPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tarjetaPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componente.TarjetaPerfil tarjetaPerfil1;
    // End of variables declaration//GEN-END:variables
}
